anderson_bjorck_king – lom
anderson_bjorck_king Subroutine
64 statements
Source File
private subroutine anderson_bjorck_king(me, ax, bx, fax, fbx, xzero, fzero, iflag)
Modified anderson-bjorck-king method. Same as anderson_bjorck, but with an extra initial bisection step.
See also
Kroger & Torsten, "On-Line Trajectory Generation in Robotic Systems", 2010. https://link.springer.com/content/pdf/bbm%3A978-3-642-05175-3%2F1.pdf
Arguments
Type Intent Optional Attributes Name
class(anderson_bjorck_king_solver), intent(inout) :: me
real(kind=wp), intent(in) :: ax
left endpoint of initial interval
real(kind=wp), intent(in) :: bx
right endpoint of initial interval
real(kind=wp), intent(in) :: fax
f(ax)
real(kind=wp), intent(in) :: fbx
f(ax)
real(kind=wp), intent(out) :: xzero
abscissa approximating a zero of f in the interval ax,bx
real(kind=wp), intent(out) :: fzero
value of f at the root (f(xzero))
integer, intent(out) :: iflag
status flag (0=root found, -2=max iterations reached)
Calls
Contents
Source Code
anderson_bjorck_king
Source Code
    subroutine anderson_bjorck_king(me,ax,bx,fax,fbx,xzero,fzero,iflag)
    implicit none
    class(anderson_bjorck_king_solver),intent(inout) :: me
    real(wp),intent(in)    :: ax      !! left endpoint of initial interval
    real(wp),intent(in)    :: bx      !! right endpoint of initial interval
    real(wp),intent(in)    :: fax     !! `f(ax)`
    real(wp),intent(in)    :: fbx     !! `f(ax)`
    real(wp),intent(out)   :: xzero   !! abscissa approximating a zero of `f` in the interval `ax`,`bx`
    real(wp),intent(out)   :: fzero   !! value of `f` at the root (`f(xzero)`)
    integer,intent(out)    :: iflag   !! status flag (`0`=root found, `-2`=max iterations reached)
    integer :: i !! counter
    logical :: root_found !! convergence in x
    real(wp) :: x1,x2,x3,f1,f2,f3,g,f1tmp
    ! initialize:
    iflag = 0
    x1    = ax
    x2    = bx
    f1    = fax
    f2    = fbx
    ! main loop:
    do i = 1,me%maxiter
        ! bisection step:
        x3 = bisect(x1,x2)
        ! calculate f3:
        f3 = me%f(x3)
        if (abs(f3)<=me%ftol)  then  ! f3 is a root
            xzero = x3
            fzero = f3
            exit
        end if
        ! determine a new inclusion interval:
        if (f2*f3<0.0_wp) then
            ! zero lies between x2 and x3
            x1 = x2
            x2 = x3
            f1 = f2
            f2 = f3
        else
            ! zero lies between x1 and x3
            x2 = x3
            f2 = f3
        end if
        ! secant step:
        x3 = secant(x1,x2,f1,f2,ax,bx)
        ! calculate f3:
        f3 = me%f(x3)
        if (abs(f3)<=me%ftol)  then  ! f3 is a root
            xzero = x3
            fzero = f3
            exit
        end if
        ! determine a new inclusion interval:
        if (f2*f3<0.0_wp) then
            ! zero lies between x2 and x3
            x1 = x2
            x2 = x3
            f1 = f2
            f2 = f3
            f1tmp = f1
        else
            ! zero lies between x1 and x3
            g = 1.0_wp-f3/f2
            if (g<=0.0_wp) g = 0.5_wp
            x2 = x3
            f1tmp = f1
            f1 = g*f1
            f2 = f3
        end if
        ! check for convergence:
        root_found = me%converged(x1,x2)
        if (root_found .or. i == me%maxiter) then
            call choose_best(x1,x2,f1tmp,f2,xzero,fzero)
            if (.not. root_found) iflag = -2  ! max iterations reached
            exit
        end if
    end do
    end subroutine anderson_bjorck_king
Call graph
anderson_bjorck_king calls choose_best, secant, bisect
secant calls bisect