bisect – lom
bisect Function
6 statements
Source File
private pure function bisect(x1, x2) result(x3)
Bisection step.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: x1
real(kind=wp), intent(in) :: x2
Return Value real(kind=wp)
point half way between x1 and x2
Called by
Contents
Source Code
bisect
Source Code
    pure function bisect(x1,x2) result(x3)
    implicit none
    real(wp),intent(in) :: x1,x2
    real(wp) :: x3 !! point half way between x1 and x2
    x3 = (x1 + x2) / 2.0_wp
    end function bisect
Call graph
zhang calls bisect, secant
muller calls bisect
regula_falsi_step calls bisect
bisection calls bisect
secant calls bisect
bdqrf calls bisect
ridders calls bisect
anderson_bjorck_king calls bisect, secant
illinois calls regula_falsi_step
regula_falsi calls regula_falsi_step
pegasus calls secant
anderson_bjorck calls secant