compute_crtpb_parameter – lom
compute_crtpb_parameter Function
7 statements
Source File
public pure function compute_crtpb_parameter(mu1, mu2) result(mu)
Compute , the normalized CRTBP parameter. It is equal to .
Note
The inputs can either be mu's or masses, as long are they are both the same units.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: mu1
grav param for body 1
real(kind=wp), intent(in) :: mu2
grav param for body 2
Return Value real(kind=wp)
CRTBP parameter
Called by
Contents
Source Code
compute_crtpb_parameter
Source Code
    pure function compute_crtpb_parameter(mu1,mu2) result(mu)
    implicit none
    real(wp),intent(in) :: mu1  !! grav param for body 1 \([km^3/s^2]\)
    real(wp),intent(in) :: mu2  !! grav param for body 2 \([km^3/s^2]\)
    real(wp)            :: mu   !! CRTBP parameter \(\mu\)
    mu = mu2 / (mu1 + mu2)
    end function compute_crtpb_parameter
Call graph
halo_test_2 calls compute_crtpb_parameter, halo_to_rv_diffcorr
halo_to_rv_diffcorr calls compute_crtpb_parameter, halo_to_rv
crtbp_test calls compute_crtpb_parameter
crtbp_propagation_test calls compute_crtpb_parameter
halo_to_rv calls compute_crtpb_parameter
dro_test calls compute_crtpb_parameter
halo_test calls compute_crtpb_parameter, halo_to_rv
halo_orbit_test calls halo_to_rv
fat_tests calls crtbp_test, halo_orbit_test