cross – lom
cross Function
Jacob Williams
7 statements
Source File
public pure function cross(r, v) result(rxv)
Cross product of two 3x1 vectors
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: r
real(kind=wp), intent(in), dimension(3) :: v
Return Value real(kind=wp),dimension(3)
Called by
Contents
Source Code
cross
Source Code
    pure function cross(r,v) result(rxv)
    implicit none
    real(wp),dimension(3),intent(in) :: r
    real(wp),dimension(3),intent(in) :: v
    real(wp),dimension(3)            :: rxv
    rxv = [r(2)*v(3) - v(2)*r(3), &
           r(3)*v(1) - v(3)*r(1), &
           r(1)*v(2) - v(1)*r(2) ]
    end function cross
Call graph
bplane calls cross, ucross
distance_from_point_to_line calls cross
compute_vinf_vectors calls cross
box_product calls cross
rv_to_orbital_elements calls cross
get_c_cdot_two_body_rotating calls cross
axis_angle_rotation calls cross
calculate_bplane_data calls cross
angle_between_vectors calls cross
from_ijk_to_lvlh_mat calls cross
from_ijk_to_rsw_mat calls cross
cartesian_to_equinoctial calls cross
solve_lambert_gooding calls cross
ucross calls cross
from_ijk_to_rsw calls from_ijk_to_rsw_mat, from_ijk_to_rsw_rv
generate_porkchop calls solve_lambert_gooding
periapsis_raise_maneuver calls rv_to_orbital_elements
from_ijk_to_lvlh calls from_ijk_to_lvlh_mat, from_ijk_to_lvlh_rv
vector_test calls axis_angle_rotation
lambert_test_1 calls solve_lambert_gooding, solve_lambert_izzo
true_anomaly calls rv_to_orbital_elements
lambert_test_2 calls solve_lambert_gooding
elements_test calls rv_to_orbital_elements, cartesian_to_equinoctial
bplane_test calls bplane, compute_vinf_vectors, calculate_bplane_data
lambert_test calls solve_lambert_gooding, solve_lambert_izzo
solve_lambert_izzo calls ucross
sphere_of_influence_earth_moon calls angle_between_vectors
modified_equinoctial_test calls cartesian_to_equinoctial
fat_tests calls vector_test, bplane_test, lambert_test, modified_equinoctial_test, relative_motion_test
from_rsw_to_ijk_mat calls from_ijk_to_rsw
from_ijk_to_lvlh_rv calls from_ijk_to_lvlh
from_lvlh_to_ijk_mat calls from_ijk_to_lvlh
relative_motion_test calls from_ijk_to_rsw, from_ijk_to_lvlh
from_ijk_to_rsw_rv calls from_ijk_to_rsw
altitude_maintenance calls periapsis_raise_maneuver, true_anomaly
integrator_report calls from_ijk_to_lvlh
from_rsw_to_ijk calls from_rsw_to_ijk_mat, from_rsw_to_ijk_rv
from_lvlh_to_ijk calls from_lvlh_to_ijk_mat, from_lvlh_to_ijk_rv
from_rsw_to_ijk_rv calls from_rsw_to_ijk
from_lvlh_to_ijk_rv calls from_lvlh_to_ijk
cw_test calls from_lvlh_to_ijk