cube_root – lom
cube_root Function
Jacob Williams
8 statements
Source File
public pure elemental function cube_root(x) result(y)
Uses
numbers_module
Cube root of a number (real solution only).
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: x
Return Value real(kind=wp)
Called by
Contents
Source Code
cube_root
Source Code
    pure elemental function cube_root(x) result(y)
    use numbers_module, only: one,three
    implicit none
    real(wp),intent(in) :: x
    real(wp)            :: y
    real(wp),parameter :: one_third = one/three
    y = sign( abs(x) ** one_third , x )
    end function cube_root
Call graph
compute_libration_points calls cube_root
compute_libration_points_v2 calls cube_root, compute_libration_points
halo_test calls compute_libration_points, halo_to_rv
crtbp_propagation_test calls compute_libration_points
halo_to_rv calls compute_libration_points
dro_test calls compute_libration_points
crtbp_test calls compute_libration_points, compute_libration_points_v2
halo_orbit_test calls halo_to_rv
halo_to_rv_diffcorr calls halo_to_rv
fat_tests calls crtbp_test, halo_orbit_test
halo_test_2 calls halo_to_rv_diffcorr