dpmpar – lom
dpmpar Function
6 statements
Source File
public function dpmpar(i)
Replacement for the original Minpack routine.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i
Return Value real(kind=wp)
Called by
Contents
Source Code
dpmpar
Source Code
    real(wp) function dpmpar(i)
    implicit none
    integer,intent(in) :: i
    real(wp),dimension(3),parameter :: dmach = [epsilon(1.0_wp),&
                                                  tiny(1.0_wp),&
                                                  huge(1.0_wp)]
    dpmpar = dmach(i)
    end function dpmpar
Call graph
fdjac1 calls dpmpar
qrfac calls dpmpar
r1updt calls dpmpar
dogleg calls dpmpar
hybrd calls dpmpar, fdjac1, qrfac, r1updt, dogleg
hybrj calls dpmpar, qrfac, r1updt, dogleg
hybrj1 calls hybrj
hybrd1 calls hybrd
halo_to_rv_diffcorr calls hybrd1
dro_test calls hybrd1
halo_test calls hybrd1
halo_test_2 calls halo_to_rv_diffcorr