emkep – lom
emkep Function
19 statements
Source File
public pure function emkep(e1, ee)
Similar to emkepl, except input is 1-e.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: e1
real(kind=wp), intent(in) :: ee
Return Value real(kind=wp)
Called by
Contents
Source Code
emkep
Source Code
    pure function emkep(e1,ee)
    implicit none
    real(wp)            :: emkep
    real(wp),intent(in) :: e1
    real(wp),intent(in) :: ee
    real(wp) :: x, ee2, term, d, x0
    x    = e1*sin(ee)
    ee2  = -ee*ee
    term = ee
    d    = zero
    do
        d = d + two
        term = term*ee2/(d*(d + one))
        x0 = x
        x = x - term
        if (x==x0) exit
    end do
    emkep = x
    end function emkep
Call graph
pv2els calls emkep
ekepl calls emkep
els2pv calls ekepl
pv3els calls pv2els
lambert_test calls pv3els
elements_test calls pv3els, els3pv
lambert_test_2 calls pv3els, propagate
els3pv calls els2pv
propagate calls pv3els, els3pv
cw_test calls els3pv
prop_error calls propagate
fat_tests calls lambert_test
gravity_test calls els3pv
propagate_trajectory calls propagate
kepler_tests calls els3pv, prop_error
lambert_test_1 calls propagate_trajectory