orbit_check – lom
orbit_check Subroutine
10 statements
Source File
private pure subroutine orbit_check(ecc, inc, circular, equatorial)
Check the orbit for singularities.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: ecc
eccentricity
real(kind=wp), intent(in) :: inc
inclination [rad]
logical, intent(out) :: circular
is the orbit circular?
logical, intent(out) :: equatorial
is the orbit equatorial?
Called by
Contents
Source Code
orbit_check
Source Code
    pure subroutine orbit_check(ecc,inc,circular,equatorial)
    implicit none
    real(wp),intent(in) :: ecc        !! eccentricity
    real(wp),intent(in) :: inc        !! inclination [rad]
    logical,intent(out) :: circular   !! is the orbit circular?
    logical,intent(out) :: equatorial !! is the orbit equatorial?
    real(wp),parameter :: tol = 1.0e-10_wp !! tolerance for circular & equatorial checks
    circular   = ecc < tol
    equatorial = (one - abs(cos(inc))) < tol  ! 0 or 180 deg
    end subroutine orbit_check
Call graph
orbital_elements_to_rv calls orbit_check
rv_to_orbital_elements calls orbit_check
rk_test_variable_step calls orbital_elements_to_rv
true_anomaly calls rv_to_orbital_elements
elements_test calls orbital_elements_to_rv, rv_to_orbital_elements
periapsis_raise_maneuver calls rv_to_orbital_elements
altitude_maintenance calls orbital_elements_to_rv, true_anomaly, periapsis_raise_maneuver
fat_tests calls rk_test_variable_step