propagate_trajectory – lom
propagate_trajectory Subroutine
16 statements
Source File
subroutine propagate_trajectory(name, rv0)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
real(kind=wp), intent(in), dimension(6) :: rv0
Calls
Called by
Contents
Source Code
propagate_trajectory
Source Code
        subroutine propagate_trajectory(name,rv0)
        implicit none
        character(len=*),intent(in) :: name
        real(wp),dimension(6),intent(in) :: rv0
        real(wp),dimension(6) :: rv,rvf
        integer :: iunit
        open(newunit=iunit,file=trim(name),status='REPLACE')
        !propagate it:
        rv = rv0
        write(iunit,'(*(E30.16,1X,A))') rv(1),',',rv(2),',',rv(3)
        do i=1,int(day2sec)
            call propagate(mu, rv, one, rvf)
            rv = rvf
            write(iunit,'(*(E30.16,1X,A))') rv(1),',',rv(2),',',rv(3)
        end do
        close(iunit)
        end subroutine propagate_trajectory
Call graph
propagate_trajectory calls propagate
propagate calls els3pv, pv3els
els3pv calls els2pv
pv3els calls pv2els
pv2els calls shmkep, emkep
els2pv calls shkepl, ekepl, dcbsol
shkepl calls shmkep, dcubrt
ekepl calls emkep, dcbsol
dcbsol calls dcubrt
lambert_test_1 calls propagate_trajectory