prop_error – lom
prop_error Subroutine
28 statements
Source File
subroutine prop_error(x0, dt, imethod, xerr, istat)
propagate the state forward the backwards, and return the error vector.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(6) :: x0
real(kind=wp), intent(in) :: dt
integer, intent(in) :: imethod
real(kind=wp), intent(out), dimension(6) :: xerr
integer, intent(out) :: istat
Calls
Called by
Contents
Source Code
prop_error
Source Code
        subroutine prop_error(x0,dt,imethod,xerr,istat)
        !! propagate the state forward the backwards, and return
        !! the error vector.
        implicit none
        real(wp),dimension(6),intent(in)  :: x0
        real(wp),intent(in)               :: dt
        integer,intent(in)                :: imethod
        real(wp),dimension(6),intent(out) :: xerr
        integer,intent(out)               :: istat
        real(wp),dimension(6) :: rv2,rv3,rv4
        real(wp),parameter :: tol = 1.0e-15_wp !! tolerance for goodyear
        istat = 0
        select case (imethod)
        case(1)
            call propagate(mu,x0,dt,rv2)
            call propagate(mu,rv2,-dt,rv3)
        case(2)
            call kepler_shepperd(mu,x0,dt,rv2,istat)
            call kepler_shepperd(mu,rv2,-dt,rv3,istat)
        case(3)
            call kepler_goodyear_stienon_klumpp(x0,dt,mu,tol,rv2)
            call kepler_goodyear_stienon_klumpp(rv2,-dt,mu,tol,rv3)
        case(4)
            call kepler_classical(x0,dt,mu,rv2)
            call kepler_classical(rv2,-dt,mu,rv3)
        case default
            error stop 'invalid method'
        end select
        xerr = rv3 - x0
        end subroutine prop_error
Call graph
prop_error calls kepler_classical, kepler_shepperd, propagate, kepler_goodyear_stienon_klumpp
kepler_classical calls newton
propagate calls pv3els, els3pv
pv3els calls pv2els
els3pv calls els2pv
pv2els calls shmkep, emkep
els2pv calls ekepl, shkepl, dcbsol
ekepl calls emkep, dcbsol
shkepl calls shmkep, dcubrt
dcbsol calls dcubrt
kepler_tests calls prop_error