root_name_to_method – lom
root_name_to_method Function
15 statements
Source File
private pure function root_name_to_method(name) result(r)
Convert a root method name to the corresponding root_method enum type.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
method name
Return Value type(root_method)
the root_method enum type for that method
Calls
Called by
Contents
Source Code
root_name_to_method
Source Code
    pure function root_name_to_method(name) result(r)
    implicit none
    character(len=*),intent(in) :: name !! method name
    type(root_method) :: r !! the [[root_method]] enum type for that method
    integer :: i !! counter
    character(len=len(name)) :: name_lowercase !! lowercase version of `name`
    ! convert to lowercase:
    name_lowercase = lowercase(name)
    ! find the name in the list:
    do i = 1, size(set_of_root_methods)
        if (name_lowercase == set_of_root_methods(i)%name) then
            r = set_of_root_methods(i)
            return
        end if
    end do
    ! if the name was not found
    r = root_method_null
    end function root_name_to_method
Call graph
root_name_to_method calls lowercase
root_scalar_by_name calls root_name_to_method, root_scalar
root_scalar calls root_scalar_by_name
ddeabm_with_event_wrapper calls root_scalar
test calls root_scalar
solve calls root_scalar
ddeabm_with_event_wrapper_vec calls root_scalar
root_tests calls test