shmkep – lom
shmkep Function
21 statements
Source File
public pure function shmkep(g1, s)
Accurate computation of s - (1 - g1)*asinh(s) when (g1, s) is close to (0, 0)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: g1
real(kind=wp), intent(in) :: s
Return Value real(kind=wp)
Called by
Contents
Source Code
shmkep
Source Code
    pure function shmkep (g1, s)
    implicit none
    real(wp)            :: shmkep
    real(wp),intent(in) :: g1
    real(wp),intent(in) :: s
    real(wp) :: g,t,tsq,x,term,twoi1,x0
    g = one - g1
    t = s/(one + sqrt(one + s*s))
    tsq = t*t
    x = s*(g1 + g*tsq)
    term = two*g*t
    twoi1 = one
    do
        twoi1 = twoi1 + two
        term = term*tsq
        x0 = x
        x = x - term/twoi1
        if (x==x0) exit
     end do
     shmkep = x
     end function shmkep
Call graph
shkepl calls shmkep
pv2els calls shmkep
els2pv calls shkepl
pv3els calls pv2els
lambert_test calls pv3els
elements_test calls pv3els, els3pv
lambert_test_2 calls pv3els, propagate
els3pv calls els2pv
propagate calls pv3els, els3pv
cw_test calls els3pv
prop_error calls propagate
fat_tests calls lambert_test
gravity_test calls els3pv
propagate_trajectory calls propagate
kepler_tests calls els3pv, prop_error
lambert_test_1 calls propagate_trajectory