uhat_dot – lom
uhat_dot Function
Jacob Williams
15 statements
Source File
public pure function uhat_dot(u, udot) result(uhatd)
Time derivative of a unit vector.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: u
vector [u]
real(kind=wp), intent(in), dimension(3) :: udot
derivative of vector [du/dt]
Return Value real(kind=wp),dimension(3)
derivative of unit vector [d(uhat)/dt]
Called by
Contents
Source Code
uhat_dot
Source Code
    pure function uhat_dot(u,udot) result(uhatd)
    implicit none
    real(wp),dimension(3),intent(in) :: u      !! vector [`u`]
    real(wp),dimension(3),intent(in) :: udot   !! derivative of vector [`du/dt`]
    real(wp),dimension(3)            :: uhatd  !! derivative of unit vector [`d(uhat)/dt`]
    real(wp)              :: umag  !! vector magnitude
    real(wp),dimension(3) :: uhat  !! unit vector
    umag = norm2(u)
    if (umag == zero) then  !singularity
        uhatd = zero
    else
        uhat = u / umag
        uhatd = ( udot - dot_product(uhat,udot)*uhat ) / umag
    end if
    end function uhat_dot
Call graph
from_ijk_to_lvlh_mat calls uhat_dot
from_ijk_to_rsw_mat calls uhat_dot
from_ijk_to_lvlh calls from_ijk_to_lvlh_mat, from_ijk_to_lvlh_rv
from_ijk_to_rsw calls from_ijk_to_rsw_mat, from_ijk_to_rsw_rv
from_lvlh_to_ijk_mat calls from_ijk_to_lvlh
from_ijk_to_lvlh_rv calls from_ijk_to_lvlh
integrator_report calls from_ijk_to_lvlh
from_rsw_to_ijk_mat calls from_ijk_to_rsw
relative_motion_test calls from_ijk_to_lvlh, from_ijk_to_rsw
from_ijk_to_rsw_rv calls from_ijk_to_rsw
from_rsw_to_ijk calls from_rsw_to_ijk_mat, from_rsw_to_ijk_rv
from_lvlh_to_ijk calls from_lvlh_to_ijk_mat, from_lvlh_to_ijk_rv
fat_tests calls relative_motion_test
cw_test calls from_lvlh_to_ijk
from_rsw_to_ijk_rv calls from_rsw_to_ijk
from_lvlh_to_ijk_rv calls from_lvlh_to_ijk