unit – lom
unit Function
Jacob Williams
12 statements
Source File
public pure function unit(r) result(u)
Unit vector
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: r
Return Value real(kind=wp),dimension(size(r))
Called by
Contents
Source Code
unit
Source Code
    pure function unit(r) result(u)
    implicit none
    real(wp),dimension(:),intent(in) :: r
    real(wp),dimension(size(r))      :: u
    real(wp) :: rmag
    rmag = norm2(r)
    if (rmag==zero) then
        u = zero
    else
        u = r / rmag
    end if
    end function unit
Call graph
bplane calls unit, ucross
axis_angle_rotation_to_rotation_matrix calls unit
get_c_cdot_two_body_rotating calls unit
axis_angle_rotation calls unit
calculate_bplane_data calls unit
from_ijk_to_lvlh_mat calls unit
solve_lambert_izzo calls unit, ucross
from_ijk_to_rsw_mat calls unit
cartesian_to_equinoctial calls unit
altitude_maintenance calls unit
solve_lambert_gooding calls unit
ucross calls unit
from_ijk_to_rsw calls from_ijk_to_rsw_mat, from_ijk_to_rsw_rv
generate_porkchop calls solve_lambert_gooding
lambert_test_1 calls solve_lambert_izzo, solve_lambert_gooding
from_ijk_to_lvlh calls from_ijk_to_lvlh_mat, from_ijk_to_lvlh_rv
vector_test calls axis_angle_rotation_to_rotation_matrix, axis_angle_rotation
lambert_test_2 calls solve_lambert_gooding
elements_test calls cartesian_to_equinoctial
bplane_test calls bplane, calculate_bplane_data
lambert_test calls solve_lambert_izzo, solve_lambert_gooding
modified_equinoctial_test calls cartesian_to_equinoctial
fat_tests calls vector_test, bplane_test, lambert_test, modified_equinoctial_test, relative_motion_test
from_rsw_to_ijk_mat calls from_ijk_to_rsw
from_ijk_to_lvlh_rv calls from_ijk_to_lvlh
from_lvlh_to_ijk_mat calls from_ijk_to_lvlh
relative_motion_test calls from_ijk_to_rsw, from_ijk_to_lvlh
from_ijk_to_rsw_rv calls from_ijk_to_rsw
integrator_report calls from_ijk_to_lvlh
from_rsw_to_ijk calls from_rsw_to_ijk_mat, from_rsw_to_ijk_rv
from_lvlh_to_ijk calls from_lvlh_to_ijk_mat, from_lvlh_to_ijk_rv
from_rsw_to_ijk_rv calls from_rsw_to_ijk
from_lvlh_to_ijk_rv calls from_lvlh_to_ijk
cw_test calls from_lvlh_to_ijk