wrap_angle – lom
wrap_angle Function
7 statements
Source File
public pure elemental function wrap_angle(a) result(r)
Wrap an angle (in rad) from -pi to pi.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: a
Return Value real(kind=wp)
Called by
Contents
Source Code
wrap_angle
Source Code
    pure elemental function wrap_angle(a) result(r)
    implicit none
    real(wp),intent(in) :: a
    real(wp)            :: r
    r = mod(a,twopi)
    if (abs(r)>pi) r = r - sign(twopi,r)
    end function wrap_angle
Call graph
rv_to_orbital_elements calls wrap_angle
halo_to_rv_diffcorr calls wrap_angle
elements_test calls rv_to_orbital_elements
halo_test_2 calls halo_to_rv_diffcorr
true_anomaly calls rv_to_orbital_elements
periapsis_raise_maneuver calls rv_to_orbital_elements
altitude_maintenance calls true_anomaly, periapsis_raise_maneuver