root_scalar – lom
root_scalar Interface
3 statements
Source File
public interface root_scalar
Calls
Called by
Contents
Module Procedures
root_scalar_by_name root_scalar_by_type
Module Procedures
private subroutine root_scalar_by_name(method, fun, ax, bx, xzero, fzero, iflag, ftol, rtol, atol, maxiter, fax, fbx, bisect_on_failure)
Non-object-oriented wrapper.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: method
the method to use
procedure(func2) :: fun
user function to find the root of
real(kind=wp), intent(in) :: ax
left endpoint of initial interval
real(kind=wp), intent(in) :: bx
right endpoint of initial interval
real(kind=wp), intent(out) :: xzero
abscissa approximating a zero of f in the interval ax,bx
real(kind=wp), intent(out) :: fzero
value of f at the root (f(xzero))
integer, intent(out) :: iflag
status flag (-1=error, 0=root found, -999=invalid method)
real(kind=wp), intent(in), optional :: ftol
absolute tolerance for f=0
real(kind=wp), intent(in), optional :: rtol
relative tol for x
real(kind=wp), intent(in), optional :: atol
absolute tol for x
integer, intent(in), optional :: maxiter
maximum number of iterations
real(kind=wp), intent(in), optional :: fax
if f(ax) is already known, it can be input here
real(kind=wp), intent(in), optional :: fbx
if f(bx) is already known, it can be input here
logical, intent(in), optional :: bisect_on_failure
if true, then if the specified method fails, it will be retried using the bisection method. (default is False). Note that this can use up to maxiter additional function evaluations.
private subroutine root_scalar_by_type(method, fun, ax, bx, xzero, fzero, iflag, ftol, rtol, atol, maxiter, fax, fbx, bisect_on_failure)
Non-object-oriented wrapper.
Arguments
Type Intent Optional Attributes Name
type(root_method), intent(in) :: method
the method to use
procedure(func2) :: fun
user function to find the root of
real(kind=wp), intent(in) :: ax
left endpoint of initial interval
real(kind=wp), intent(in) :: bx
right endpoint of initial interval
real(kind=wp), intent(out) :: xzero
abscissa approximating a zero of f in the interval ax,bx
real(kind=wp), intent(out) :: fzero
value of f at the root (f(xzero))
integer, intent(out) :: iflag
status flag (-1=error, 0=root found, -999=invalid method)
real(kind=wp), intent(in), optional :: ftol
absolute tolerance for f=0
real(kind=wp), intent(in), optional :: rtol
relative tol for x
real(kind=wp), intent(in), optional :: atol
absolute tol for x
integer, intent(in), optional :: maxiter
maximum number of iterations
real(kind=wp), intent(in), optional :: fax
if f(ax) is already known, it can be input here
real(kind=wp), intent(in), optional :: fbx
if f(bx) is already known, it can be input here
logical, intent(in), optional :: bisect_on_failure
if true, then if the specified method fails, it will be retried using the bisection method. (default is False). Note that this can use up to maxiter additional function evaluations.
Call graph
root_scalar calls root_scalar_by_name, root_scalar_by_type
root_scalar_by_name calls root_scalar, root_name_to_method
root_name_to_method calls lowercase
solve calls root_scalar
ddeabm_with_event_wrapper_vec calls root_scalar
test calls root_scalar
ddeabm_with_event_wrapper calls root_scalar
root_tests calls test