fat_tests – lom
fat_tests Program
Jacob Williams
24 statements
Source File
Uses
fortran_astrodynamics_toolkit
Unit test program for the Fortran Astrodynamics Toolkit
Calls
Contents
Source Code
fat_tests
Source Code
    program fat_tests
    use fortran_astrodynamics_toolkit
    implicit none
    call brent_test()
    call ephemeris_test()
    call vector_test()
    call lambert_test()
    call complex_step_test()
    call time_module_test()
    call geopotential_module_test()
    call iau_test()
    call relative_motion_test()
    call crtbp_test()
    call bplane_test()
    call direct_inverse_test()
    call modified_equinoctial_test()
    call transformation_module_test()
    call step_size_test()
    call rk_test()
    call rk_test_variable_step()
    call standish_module_test()
    call halo_orbit_test()
    call eispack_test()
    end program fat_tests
Call graph
fat_tests calls direct_inverse_test, transformation_module_test, geopotential_module_test, modified_equinoctial_test, halo_orbit_test, ephemeris_test, brent_test, relative_motion_test, crtbp_test, rk_test, eispack_test, time_module_test, vector_test, step_size_test, standish_module_test, rk_test_variable_step, iau_test, bplane_test, lambert_test, complex_step_test
direct_inverse_test calls inverse, direct
transformation_module_test calls ecliptic_frame, two_body_rotating_pulsating_frame, icrf_frame
geopotential_module_test calls get_random_number, number_of_coefficients, spherical_to_cartesian
modified_equinoctial_test calls equinoctial_to_cartesian, cartesian_to_equinoctial, modified_equinoctial_derivs
halo_orbit_test calls halo_to_rv
relative_motion_test calls from_ijk_to_lvlh, from_ijk_to_rsw
crtbp_test calls compute_jacobi_constant, compute_libration_points, crtbp_derivs, compute_crtpb_parameter, compute_libration_points_v2, crtbp_derivs_with_stm
eispack_test calls compute_eigenvalues_and_eigenvectors
time_module_test calls julian_date
vector_test calls axis_angle_rotation_to_rotation_matrix, axis_angle_rotation, rotation_matrix
standish_module_test calls et_to_jd, helio
rk_test_variable_step calls orbital_elements_to_rv
iau_test calls icrf_to_iau_moon, icrf_to_iau_earth
bplane_test calls bplane, compute_vinf_vectors, calculate_bplane_data
lambert_test calls pv3els, get_random_number, solve_lambert_izzo, solve_lambert_arorarussell, solve_lambert_gooding
complex_step_test calls forward_diff, complex_step_derivative, central_diff_4, central_diff
bplane calls unit, ucross, cross
ecliptic_frame calls ecliptic_frame_constructor
julian_date calls julian_date_realsec, julian_date_intsec
axis_angle_rotation_to_rotation_matrix calls cross_matrix, unit
pv3els calls pv2els
axis_angle_rotation calls unit, cross
orbital_elements_to_rv calls orbit_check
two_body_rotating_pulsating_frame calls two_body_rotating_pulsating_frame_constructor
cartesian_to_equinoctial calls unit, cross
solve_lambert_izzo calls unit, ucross
halo_to_rv calls compute_libration_points, compute_crtpb_parameter
compute_eigenvalues_and_eigenvectors calls rg
icrf_frame calls icrf_frame_constructor
from_ijk_to_lvlh calls from_ijk_to_lvlh_rv, from_ijk_to_lvlh_mat
compute_libration_points calls cube_root
icrf_to_iau_moon calls iau_rotation_matrix
helio calls el2op, op2ec, tbl, calcelements
icrf_to_iau_earth calls iau_rotation_matrix
solve_lambert_gooding calls unit, cross
from_ijk_to_rsw calls from_ijk_to_rsw_rv, from_ijk_to_rsw_mat
compute_vinf_vectors calls cross
compute_libration_points_v2 calls compute_libration_points, cube_root
calculate_bplane_data calls unit, cross
iau_rotation_matrix calls rotation_matrix
from_ijk_to_lvlh_rv calls from_ijk_to_lvlh
from_ijk_to_rsw_rv calls from_ijk_to_rsw
julian_date_realsec calls julian_day
from_ijk_to_rsw_mat calls unit, cross, uhat_dot
rg calls hqr2, eltran, hqr, elmhes, balbak, balanc
pv2els calls shmkep, emkep
julian_date_intsec calls julian_date_realsec
ucross calls unit, cross
calcelements calls kepler
from_ijk_to_lvlh_mat calls unit, cross, uhat_dot
hqr2 calls cdiv