halo_test_2 – lom
halo_test_2 Program
Jacob Williams
85 statements
Source File
Uses
fortran_astrodynamics_toolkit
pyplot_module
Halo Orbit generation example (Earth-Moon system).
Note
Requires pyplot-fortran module.
Calls
Contents
Variables
mu_earth mu_moon em_distance A_z t1 n Az_step rv phi w z lambda libpoint i j Az info sol_family period ierr mu e v n_results
Source Code
halo_test_2
Variables
Type Attributes Name Initial
real(kind=wp), parameter :: mu_earth = 398600.436233_wp
real(kind=wp), parameter :: mu_moon = 4902.800076_wp
real(kind=wp), parameter :: em_distance = 384400.0_wp
earth-moon distance [km]
real(kind=wp), parameter :: A_z = 1000.0_wp
initial halo z-amplitude
real(kind=wp), parameter :: t1 = 0.0_wp
tau for halo orbit
integer, parameter :: n = 6
number of state variables
real(kind=wp), parameter :: Az_step = 1000.0_wp
Az step size (km)
real(kind=wp), dimension(n) :: rv
halo orbit initial state
real(kind=wp), dimension(n,n) :: phi
monodromy matrix
real(kind=wp), dimension(n,2) :: w
real and and imaginary parts of the eigenvalues of phi
real(kind=wp), dimension(n,n) :: z
real and imaginary parts of the eigenvectors of phi
complex(kind=wp), dimension(n) :: lambda
eigenvalues of phi
integer :: libpoint
libration point (1,2,3)
integer :: i
counter
integer :: j
counter
real(kind=wp) :: Az
halo z-amplitude (km)
integer :: info
minpack status code
integer :: sol_family
1 or 3 (family)
real(kind=wp) :: period
halo period (normalized time)
integer :: ierr
output flag from compute_eigenvalues_and_eigenvectors
real(kind=wp) :: mu
CRTBP parameter
real(kind=wp), dimension(:), allocatable :: e
real eigenvalues
real(kind=wp), dimension(:,:), allocatable :: v
normalized eigenvectors associated with the real eigenvalues
integer :: n_results
number of real eigenvalues
Source Code
    program halo_test_2
    use fortran_astrodynamics_toolkit, wp => fat_wp
    use pyplot_module
    implicit none
    real(wp),parameter :: mu_earth = 398600.436233_wp    !! \( \mu_{Earth} ~ (\mathrm{km}^3/\mathrm{s}^2) \)
    real(wp),parameter :: mu_moon  = 4902.800076_wp      !! \( \mu_{Moon}  ~ (\mathrm{km}^3/\mathrm{s}^2) \)
    real(wp),parameter :: em_distance = 384400.0_wp      !! earth-moon distance [km]
    real(wp),parameter :: A_z = 1000.0_wp    !! initial halo z-amplitude
    real(wp),parameter :: t1 = 0.0_wp        !! tau for halo orbit
    integer,parameter  :: n  = 6             !! number of state variables
    real(wp),parameter :: Az_step =1000.0_wp !! Az step size (km)
    real(wp),dimension(n)    :: rv     !! halo orbit initial state
    real(wp),dimension(n,n)  :: phi    !! monodromy matrix
    real(wp),dimension(n,2)  :: w      !! real and and imaginary parts of the eigenvalues of `phi`
    real(wp),dimension(n,n)  :: z      !! real and imaginary parts of the eigenvectors of `phi`
    complex(wp),dimension(n) :: lambda !! eigenvalues of `phi`
    integer  :: libpoint         !! libration point (1,2,3)
    integer  :: i                !! counter
    integer  :: j                !! counter
    real(wp) :: Az               !! halo z-amplitude (km)
    integer  :: info             !! minpack status code
    integer  :: sol_family       !! 1 or 3 (family)
    real(wp) :: period           !! halo period (normalized time)
    integer  :: ierr             !! output flag from [[compute_eigenvalues_and_eigenvectors]]
    real(wp) :: mu               !! CRTBP parameter
    real(wp),dimension(:),allocatable   :: e !! real eigenvalues
    real(wp),dimension(:,:),allocatable :: v !! normalized eigenvectors associated with the real eigenvalues
    integer :: n_results !! number of real eigenvalues
    mu = compute_crtpb_parameter(mu_earth,mu_moon)
    do libpoint = 1, 3
        write(*,*) ''
        write(*,*) '---------------------------'
        write(*,*) ' libpoint: ', libpoint
        write(*,*) '---------------------------'
        write(*,*) ''
        do sol_family = 1, 3, 2
            write(*,*) ''
            write(*,*) ' family: ', sol_family
            write(*,*) ''
            do i=1,10
                Az = A_z+(i-1)*Az_step
                call halo_to_rv_diffcorr(libpoint,mu_earth,mu_moon,em_distance,&
                                            Az,sol_family,t1,rv,info,period)
                if (info/=1) error stop 'error'
                write(*,*) ''
                write(*,*) az,' [', rv(1),',',&
                                    rv(2),',',&
                                    rv(3),',',&
                                    rv(4),',',&
                                    rv(5),',',&
                                    rv(6),']', period
                if (libpoint==1 .and. sol_family==1 .and. i==1) then
                    call compute_halo_monodromy_matrix(mu,rv,period,phi)
                    write(*,*) ''
                    write(*,*) 'monodromy matrix:'
                    write(*,*) ''
                    call print_matrix(phi)
                    write(*,*) ''
                    ! general method:
                    call compute_eigenvalues_and_eigenvectors(6, phi, w, z, ierr)
                    write(*,*) ''
                    write(*,*) 'eigenvalues:'
                    write(*,*) ''
                    call print_matrix(w)
                    write(*,*) ''
                    write(*,*) 'eigenvectors:'
                    write(*,*) ''
                    call print_matrix(z)
                    write(*,*) ''
                    ! quicker method for just the eigenvalues:
                    call compute_monodromy_matrix_eigenvalues(phi,lambda)
                    write(*,*) ''
                    write(*,*) 'lambda:'
                    write(*,*) lambda
                    write(*,*) ''
                    ! normalized values:
                    call compute_real_eigenvalues_and_normalized_eigenvectors(6, phi, e, v, n_results, ierr)
                    write(*,*) ''
                    write(*,*) 'real eigenvalues:', e
                    write(*,*) ''
                    write(*,*) 'normalized eigenvectors:'
                    write(*,*) ''
                    call print_matrix(v)
                    write(*,*) ''
                    ! the determinant should be 1.0 since matrix is sympletic
                    write(*,*) ''
                    write(*,*) '-----'
                    write(*,*) 'determinate of phi: ', matrix_determinant(6,phi)
                    write(*,*) '-----'
                    write(*,*) ''
                end if
            end do
        end do
    end do
    end program halo_test_2
Call graph
halo_test_2 calls compute_real_eigenvalues_and_normalized_eigenvectors, halo_to_rv_diffcorr, compute_monodromy_matrix_eigenvalues, print_matrix, compute_eigenvalues_and_eigenvectors, compute_crtpb_parameter, matrix_determinant, compute_halo_monodromy_matrix
compute_real_eigenvalues_and_normalized_eigenvectors calls compute_eigenvalues_and_eigenvectors
halo_to_rv_diffcorr calls compute_crtpb_parameter, halo_to_rv, hybrd1, wrap_angle
compute_monodromy_matrix_eigenvalues calls matrix_trace
compute_eigenvalues_and_eigenvectors calls rg
matrix_determinant calls matrix_determinant
rg calls hqr2, eltran, hqr, elmhes, balbak, balanc
halo_to_rv calls compute_crtpb_parameter, compute_libration_points
hybrd1 calls hybrd
hqr2 calls cdiv
compute_libration_points calls cube_root
hybrd calls fdjac1, dpmpar, r1updt, r1mpyq, dogleg, qform, qrfac, enorm
fdjac1 calls dpmpar
r1updt calls dpmpar
dogleg calls dpmpar, enorm
qrfac calls dpmpar, enorm